### ISSUE TITLE
[WEB Improvement] : Cards

### ISSUE THREAD

**Issue by Puskar-Roy2** [Puskar-Roy/create-my-api#10]
### Quick Description 🛠️

ddbdbdbd

### Select the open-source program you're contributing to

SSOC

### Adherence to Code of Conduct

- [X] I adhere to the [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

**Comment by Puskar-Roy** [comment]
Hello @Puskar-Roy2👋! Thank you for opening this issue and showing interest in contributing to our project!🚀
We appreciate your participation and look forward to your contributions. Please use the command /gdsc to self-assign the issue if you're interested.
This issue is a great opportunity for us to enhance our project, and we're excited to have you on board! Please make sure to follow our [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Feel free to reach out to us on [Linked IN](https://www.linkedin.com/in/puskar-roy/) if you need any help or have any questions.❤️
